"""modify uid and display_name field

Revision ID: faaabdc9d907
Revises: 850b64ca8c00
Create Date: 2025-08-19 02:10:40.864219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faaabdc9d907'
down_revision = '850b64ca8c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('display_name', sa.String(length=50), nullable=False))
        batch_op.drop_column('id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_column('display_name')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
